# Generated by Django 6.0.2 on 2026-03-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelroom',
            name='description',
        ),
        migrations.RemoveField(
            model_name='hotelroom',
            name='room_type',
        ),
        migrations.AddField(
            model_name='hotelroom',
            name='location',
            field=models.CharField(db_index=True, default='unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotelroom',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hotelroom',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
