# Generated by Django 6.0.2 on 2026-03-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_hotelroom_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelroom',
            name='is_available',
        ),
        migrations.AddField(
            model_name='hotelroom',
            name='available_rooms',
            field=models.PositiveIntegerField(default=10, help_text='Rooms currently empty'),
        ),
        migrations.AddField(
            model_name='hotelroom',
            name='total_rooms',
            field=models.PositiveIntegerField(default=10, help_text='Total capacity of this hotel/camp'),
        ),
    ]
